"""Write docs/validation.md and the validation chart (a small hand-built SVG) from a sweep."""

from html import escape

import pandas as pd

from marketmood_ml.model.config import GATES, LABELS

COLOURS = {"Bull": "#2e9e5b", "Sideways": "#d9a21b", "Crisis": "#d64545"}


def validation_markdown(results, chosen, status, chart_name="validation_chart.svg"):
    config, model, out, m = chosen
    gate_names = {
        "periods": f"Reference periods >= {GATES['periods_correct_min']} of 6",
        "macro_f1": f"Macro-F1 vs reference labels >= {GATES['macro_f1_min']:.2f}",
        "fidelity": f"Surrogate fidelity >= {GATES['fidelity_min']:.0%}",
        "stability": f"Confirmed switches per year (test) < {GATES['switches_per_year_max']}",
        "transition_lag": f"2020 crash transition lag <= {GATES['transition_lag_max']} trading days",
    }
    values = {
        "periods": f"{m['periods_correct']} of 6",
        "macro_f1": f"{m['macro_f1']:.3f}",
        "fidelity": f"{m['surrogate_fidelity']:.1%}",
        "stability": f"{m['switches_per_year_test']:.1f}",
        "transition_lag": str(m["transition_lag_2020"]),
    }
    t = model.train
    lines = [
        "# Model validation",
        "",
        "Generated by `uv run mm-train`; do not edit by hand. Method and decisions:",
        "[ADR 0001](adr/0001-regime-model.md).",
        "",
        f"**Released model:** `{model.version}` (configuration {config.name}: {config.description}).",
        f"**Status:** {status}"
        + (" — at least one Gate G2 target is not met." if status != "validated" else "."),
        "",
        f"Training data {t['start']} to {t['end']} ({t['rows']} days); "
        f"test data {t['test_start']} to {t['test_end']} ({t['test_rows']} days). "
        "The HMM, the scaler and the state names are fitted on training days only.",
        f"Best of {len(config.seeds)} seeds: seed {m['seed']}, "
        f"training log-likelihood {m['log_likelihood']}.",
        "",
        "## Gate G2",
        "",
        "| Target | Result | Pass |",
        "|---|---|---|",
    ]
    for key, name in gate_names.items():
        lines.append(f"| {name} | {values[key]} | {'yes' if m['gates'][key] else '**no**'} |")
    lines += [
        "",
        "## Reference periods (confirmed labels, causal)",
        "",
        "| Period | Event | Expected | Model (share of days) | Correct |",
        "|---|---|---|---|---|",
    ]
    for p in m["periods"]:
        lines.append(
            f"| {p['start']} to {p['end']} | {p['event']} | {' or '.join(p['expected'])} | "
            f"{p['top']} ({p['share']:.0%}) | {'yes' if p['correct'] else '**no**'} |"
        )
    lines += [
        "",
        "All six periods fall inside the training window. The labels are causal (each day uses only",
        "data up to that day), but the model's parameters were learnt from the training years, so this",
        "is an in-sample check. The walk-forward section below is the fully out-of-sample one.",
        "",
    ]
    lines += _walk_forward_section(m.get("walk_forward"))
    lines += [
        "## Agreement with the objective reference labels",
        "",
        f"Macro-F1: model {m['macro_f1']:.3f} (all days), {m['macro_f1_test']:.3f} (test period); "
        f"simple rule-based benchmark {m['macro_f1_benchmark']:.3f}.",
        "",
        "Confusion matrix, rows = reference label, columns = model's confirmed label:",
        "",
        _confusion_table(m["confusion"]),
        "",
        "Benchmark (VIX > 25 and drawdown_60d < -10% → Crisis; sharpe_60d > 0 → Bull; else Sideways):",
        "",
        _confusion_table(m["confusion_benchmark"]),
        "",
        "## Stability, confidence, explanations",
        "",
        f"- Confirmed regime switches per year: {m['switches_per_year_test']:.1f} (test), "
        f"{m['switches_per_year_all']:.1f} (all days).",
        f"- Days per confirmed label: {_days(m['label_days'])}.",
        f"- Mean confidence (filtered probability of the label shown): {m['mean_confidence']:.2f}. "
        "HMM probabilities are overconfident; treat them as a ranking, not a calibrated chance.",
        f"- Surrogate fidelity: {m['surrogate_fidelity']:.1%} on all days; "
        f"{m['surrogate_fidelity_test']:.1%} on the test period when trained on the training period only.",
        f"- Latest day {m['latest']['date']}: {m['latest']['confirmed_label']} "
        f"(confidence {m['latest']['confidence']:.2f}).",
        "",
        "## Backtest (research result, not advice)",
        "",
        "100% NIFTY in Bull, 60% in Sideways, 30% in Crisis, rest at 6% a year; 1-day delay; 0.1% costs;",
        "price index without dividends.",
        "",
        "| Period | Strategy CAGR | Buy-and-hold CAGR | Strategy max drawdown | Buy-and-hold max drawdown "
        "| Strategy Sharpe | Buy-and-hold Sharpe | Weight changes |",
        "|---|---|---|---|---|---|---|---|",
        _backtest_row("All days", m["backtest_all"]),
        _backtest_row("Test period", m["backtest_test"]),
        "",
        "## Validation chart",
        "",
        f"![NIFTY 50 coloured by confirmed regime]({chart_name})",
        "",
        "## Every configuration in the sweep (pre-registered, in priority order)",
        "",
        "| Config | Description | Periods | Macro-F1 | Fidelity | Switches/yr (test) | 2020 lag "
        "| All gates |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for c, _model, _out, rm in results:
        mark = " (released)" if c.name == config.name else ""
        lines.append(
            f"| {c.name}{mark} | {c.description} | {rm['periods_correct']}/6 | {rm['macro_f1']:.3f} | "
            f"{rm['surrogate_fidelity']:.1%} | {rm['switches_per_year_test']:.1f} | "
            f"{rm['transition_lag_2020']} | {'yes' if rm['passed'] else 'no'} |"
        )
    lines += [
        "",
        "Selection rule (fixed before the sweep): the first configuration that passes every gate; if none",
        "does, the most reference periods correct, then the highest macro-F1.",
        "",
    ]
    return "\n".join(lines)


def _walk_forward_section(wf):
    if not wf:
        return []
    lines = [
        "## Fully out-of-sample check (walk-forward)",
        "",
        f"Each year from {wf['start'][:4]} is labelled by a model refitted (scaler, HMM, state names) on",
        "the earlier years only, so no day was seen by the model that labels it. Not used to pick the model.",
        "",
        "| Period | Expected | Model (share of days) | Correct |",
        "|---|---|---|---|",
    ]
    for p in wf["periods"]:
        lines.append(
            f"| {p['start']} to {p['end']} | {' or '.join(p['expected'])} | {p['top']} ({p['share']:.0%}) "
            f"| {'yes' if p['correct'] else '**no**'} |"
        )
    lines += [
        "",
        f"{wf['start']} to {wf['end']}: {wf['periods_correct']} of {wf['periods_scored']} periods correct, "
        f"macro-F1 {wf['macro_f1']:.3f}, {wf['switches_per_year']:.1f} confirmed switches per year, "
        f"2020 transition lag {wf['transition_lag_2020']} trading days.",
        "",
    ]
    return lines


def _confusion_table(conf):
    rows = ["| Reference \\ Model | " + " | ".join(LABELS) + " |", "|---|" + "---|" * len(LABELS)]
    for r in LABELS:
        rows.append(f"| {r} | " + " | ".join(str(conf[r][p]) for p in LABELS) + " |")
    return "\n".join(rows)


def _days(counts):
    return ", ".join(f"{k} {v}" for k, v in counts.items())


def _backtest_row(name, bt):
    s, b = bt["strategy"], bt["buy_hold"]
    return (
        f"| {name} | {s['cagr']:.1%} | {b['cagr']:.1%} | {s['max_drawdown']:.1%} | {b['max_drawdown']:.1%} "
        f"| {s['sharpe']:.2f} | {b['sharpe']:.2f} | {bt['weight_changes']} |"
    )


def validation_svg(frame, out, test_start, width=960, height=360, step=5):
    """NIFTY close (every `step`-th day) over background bands of the confirmed label."""
    dates = pd.to_datetime(frame["date"]).reset_index(drop=True)
    close = frame["close"].reset_index(drop=True)
    labels = list(out["confirmed_label"])
    left, right, top, bottom = 56, 12, 28, 30
    plot_w, plot_h = width - left - right, height - top - bottom
    t0, t1 = dates.iloc[0].value, dates.iloc[-1].value
    lo, hi = float(close.min()) * 0.97, float(close.max()) * 1.03

    def x(d):
        return left + (pd.Timestamp(d).value - t0) / (t1 - t0) * plot_w

    def y(v):
        return top + (hi - v) / (hi - lo) * plot_h

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" '
        f'font-family="Helvetica, Arial, sans-serif" font-size="11">',
        f'<rect width="{width}" height="{height}" fill="#ffffff"/>',
    ]
    start = 0
    for i in range(1, len(labels) + 1):  # one rectangle per run of the same label
        if i == len(labels) or labels[i] != labels[start]:
            x0 = x(dates.iloc[start])
            x1 = x(dates.iloc[i]) if i < len(labels) else left + plot_w
            parts.append(
                f'<rect x="{x0:.1f}" y="{top}" width="{max(x1 - x0, 0.6):.1f}" height="{plot_h}" '
                f'fill="{COLOURS[labels[start]]}" fill-opacity="0.28"/>'
            )
            start = i
    for year in range(dates.iloc[0].year + 1, dates.iloc[-1].year + 1):
        xx = x(pd.Timestamp(year=year, month=1, day=1))
        parts.append(f'<line x1="{xx:.1f}" y1="{top}" x2="{xx:.1f}" y2="{top + plot_h}" stroke="#00000018"/>')
        parts.append(f'<text x="{xx:.1f}" y="{height - 10}" text-anchor="middle" fill="#333">{year}</text>')
    for v in _ticks(lo, hi):
        parts.append(f'<text x="{left - 6}" y="{y(v) + 4:.1f}" text-anchor="end" fill="#333">{v:,.0f}</text>')
    xs = x(test_start)
    parts.append(
        f'<line x1="{xs:.1f}" y1="{top}" x2="{xs:.1f}" y2="{top + plot_h}" stroke="#333" '
        f'stroke-dasharray="4 3"/><text x="{xs + 4:.1f}" y="{top + 12}" fill="#333">test period</text>'
    )
    idx = list(range(0, len(close), step)) + [len(close) - 1]
    points = " ".join(f"{x(dates.iloc[i]):.1f},{y(float(close.iloc[i])):.1f}" for i in sorted(set(idx)))
    parts.append(f'<polyline points="{points}" fill="none" stroke="#1f2a44" stroke-width="1.2"/>')
    lx = left
    for name in LABELS:
        parts.append(
            f'<rect x="{lx}" y="8" width="12" height="12" fill="{COLOURS[name]}" fill-opacity="0.6"/>'
            f'<text x="{lx + 16}" y="18" fill="#333">{escape(name)}</text>'
        )
        lx += 90
    parts.append(f'<text x="{width - right}" y="18" text-anchor="end" fill="#333">NIFTY 50 close</text>')
    parts.append("</svg>")
    return "\n".join(parts) + "\n"


def _ticks(lo, hi, n=5):
    step = (hi - lo) / n
    magnitude = 10 ** (len(str(int(step))) - 1)
    step = max(magnitude, round(step / magnitude) * magnitude)
    first = (int(lo // step) + 1) * step
    return list(range(int(first), int(hi), int(step)))
